sudo: required

services:
  - xvfb

language: java

dist: xenial

jdk:
- openjdk11

branches:
  only:
  - develop
  - master
  - "/^v[0-9].*/"

cache:
  directories:
  - $HOME/.m2

install: true

before_script:
- export TZ=Europe/Berlin

script: mvn clean verify

deploy:
  provider: releases
  api_key:
    secure: LF6i/LWlzcDSwLQhEiLn/w569Sqaq6L9/5tRUlpPuxpvNZLRy20Gj0Ob77ajogzaf2Prcuh9nCLQfuiT/FAhneqsY1Z8p4BW99jfpXCLPEQVDEuzlttSkykMgjrusAVTufY0s0GCiQ7u7JLxjFjSw/i46lN6kdLIpdZeSswFf7OVZvLYnkzpygafE3xaE1RJzTwvY6jJWJ/3xmlBTSWRkWCraJf5Bfs2PveHAvQBDtrp/a6AwhUOW8G+yX71stCf8uzNB8Jv0/4BRjG9DrFisM0QIHK1c6ePza1suatyVr+qyMATwEJ8foTTm4FHgdlLcrcNjNRbubMET4QVKem5PwvGWsavq0jGQ394TUoGVzsKQ5pxII1DH2HuJ8ABexmvnpOEnfZhx1gKsdO7IP3j7Cm29hCBCxMxuAWXfO5HFMhQVMm36b3Pa4vZMj9gRgZ/0a1bdwx+4tYV/LI4mjwePOahPmh4NFEW/aMvrzKHKqUw2JYQ94siNt+vq78D1YY/VI9ISaZqsmGACFpDyZIGmT/x76V+6ONZBt53qtXX9sUr2/oQmzNzYgoNJGwXnoTq8RuKDwo7f+14+BySX/IZT9wdemlynTKsmijVO16OxEYcGSvibH6vQVVbnLrcsvmy/gRgnqpYhTcm1qHrxaXhvNVKjmXCSMGjOxsaZ1yGtUk=
  file: "./target/*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    repo: mathisdt/sdb2
