name: Build

on:
  push:
    branches:
      - "**"

jobs:
  release:
    uses: mathisdt/workflows/.github/workflows/maven.yaml@master
    with:
      script-after-maven-build: ./build-jre-distributions.sh
      files-to-release: |
        target/sdb2-without-jre.zip
        target/sdb2-bundle-linux.zip
        target/sdb2-bundle-windows.zip
    secrets: inherit

